project_id = "xlahlhjhuokpzwczqzoz"

[functions.username-signup]
verify_jwt = false

[functions.validate-invite]
verify_jwt = false

[functions.link-invite-user]
verify_jwt = false

[functions.pin-login-telemetry]
verify_jwt = false

[functions.manual-auth]
verify_jwt = false
